In [8]:
import pandas as pd
import numpy as np

In [25]:
flatdata = pd.read_csv ('Health - Health.csv')
x = flatdata.iloc [:,0:3].values
y = flatdata.iloc [:,3].values
flatdata

Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No
2     Asian        175.0         80.0                   No
3     White        180.0         88.0                  Yes
4     Asian        178.0          NaN                   No
5     Asian        172.0         72.0                  Yes
6   African        178.0         75.0                   No
7     White          NaN         89.0                  Yes
8   African        186.0         90.0                  Yes

In [26]:
from sklearn.preprocessing import LabelEncoder
x_lc=LabelEncoder()
x[:,0]=x_lc.fit_transform(x[:,0])
x

array([[2, 186.0, 90.0],
       [0, 185.0, 98.0],
       [1, 175.0, 80.0],
       [2, 180.0, 88.0],
       [1, 178.0, nan],
       [1, 172.0, 72.0],
       [0, 178.0, 75.0],
       [2, nan, 89.0],
       [0, 186.0, 90.0]], dtype=object)

In [27]:
y_lc =LabelEncoder()
y=y_lc.fit_transform(y)
y

array([1, 0, 0, 1, 0, 1, 0, 1, 1])

In [28]:
#simpleImputer
from sklearn.impute import SimpleImputer

In [29]:
mvi = SimpleImputer(missing_values = np.nan , strategy = "mean")
mvi = mvi.fit(x[:,1:3])
x[:,1:3] = mvi.transform(x[:,1:3])

In [30]:
print(x)

[[2 186.0 90.0]
 [0 185.0 98.0]
 [1 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 85.25]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 180.0 89.0]
 [0 186.0 90.0]]


In [31]:
#spliting into train test
from sklearn.model_selection import train_test_split

In [32]:
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=0)

In [35]:
X_train,y_train

(array([[1, 178.0, 85.25],
        [0, 186.0, 90.0],
        [0, 178.0, 75.0],
        [2, 180.0, 88.0],
        [2, 186.0, 90.0],
        [1, 172.0, 72.0]], dtype=object),
 array([0, 1, 0, 1, 1, 1]))

In [36]:
X_test,y_test

(array([[2, 180.0, 89.0],
        [1, 175.0, 80.0],
        [0, 185.0, 98.0]], dtype=object),
 array([1, 0, 0]))